# Generated by Django 5.2.10 on 2026-02-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approve this review for public display'),
        ),
    ]
