# Generated by Django 5.2.10 on 2026-02-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_bookreview_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='era',
            name='year',
        ),
        migrations.AlterField(
            model_name='era',
            name='name',
            field=models.CharField(db_index=True, help_text="e.g. '1810s', 'Regency Era', '1600s', 'Elizabethan Era'", max_length=50, unique=True),
        ),
    ]
