# Generated by Django 5.2.11 on 2026-02-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_cart_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF for online reading', null=True, upload_to='book_pdfs/'),
        ),
    ]
