# Generated by Django 5.2.10 on 2026-02-04 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_brand_book_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Number of items in stock'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_covers/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adminapp.book')),
            ],
        ),
    ]
